CREATE TABLE payment_checkout (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id      VARCHAR(200) NOT NULL UNIQUE,
    plan_key        VARCHAR(20) NOT NULL,
    billing_period  VARCHAR(20) NOT NULL,
    amount_centavos INTEGER NOT NULL,
    status          VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    paid_at         TIMESTAMP
);

CREATE INDEX idx_payment_checkout_user_id ON payment_checkout(user_id);
