-- Expand step: the ledger of provider webhook events already processed (TEN-147).
--
-- A provider retries a delivery until it sees a 2xx, and every retry carries the same event id.
-- That id is the idempotency key: the row is inserted in the same transaction that applies the
-- event, so a delivery that fails rolls the claim back and the retry may try again, while a
-- delivery that succeeds leaves a claim no later copy of that event can take.
--
-- The UNIQUE constraint is the whole mechanism, not an index for reads: two overlapping
-- deliveries both find no row, and the database — not the application — decides which one wins.
-- (provider, event_id) rather than event_id alone so a second provider's id space cannot
-- collide with PayMongo's.
CREATE TABLE webhook_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(40)  NOT NULL,
    event_id    VARCHAR(200) NOT NULL,
    event_type  VARCHAR(100),
    received_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_webhook_event_provider_event_id UNIQUE (provider, event_id)
);
