-- Expand step (TEN-173): merchant→category rules, category aliases, and the per-expense override.
--
-- Three shapes, one feature: a user who categorises "Jollibee" once should never categorise it
-- again, a category should answer to more than one spelling while parsing, and a single expense
-- must be able to disagree with its rule without destroying the rule for every later expense.
--
-- `merchant` and `alias` hold the ALREADY-NORMALISED key (lower-cased, punctuation and amount
-- tokens stripped — see CategoryService#merchantKey), so a plain UNIQUE is the whole lookup
-- index; there is no lower(...) expression index here because there is no mixed case to fold.
-- Both FKs cascade from the owning row: deleting a user or a category cannot leave a rule or an
-- alias pointing at nothing.

CREATE TABLE merchant_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    merchant    VARCHAR(100) NOT NULL,
    category_id BIGINT       NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uq_merchant_rules_user_merchant UNIQUE (user_id, merchant)
);

CREATE INDEX idx_merchant_rules_category ON merchant_rules (category_id);

CREATE TABLE category_aliases (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id BIGINT      NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    alias       VARCHAR(50) NOT NULL,
    created_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uq_category_aliases_user_alias UNIQUE (user_id, alias)
);

CREATE INDEX idx_category_aliases_category ON category_aliases (category_id);

-- Expand-only: a new NOT NULL column with a default, so deployed code that does not know about
-- it keeps inserting valid rows. FALSE means "this expense's category came from the rule (or from
-- nothing)"; TRUE means "a human said otherwise for this row only".
ALTER TABLE expenses ADD COLUMN category_overridden BOOLEAN NOT NULL DEFAULT FALSE;
