-- Subscription & feature-entitlement foundation. Plans and their feature grants are also ensured
-- idempotently at startup by EntitlementSeeder (the FeatureKey enum is the source of truth), so this
-- migration only creates the schema; seeding is code-driven for cross-environment consistency.

CREATE TABLE subscription_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_key    VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    price_cents INTEGER      NOT NULL DEFAULT 0,
    currency    VARCHAR(3)   NOT NULL DEFAULT 'PHP',
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE plan_features (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT      NOT NULL REFERENCES subscription_plans(id) ON DELETE CASCADE,
    feature_key VARCHAR(40) NOT NULL,
    CONSTRAINT uq_plan_feature UNIQUE (plan_id, feature_key)
);
CREATE INDEX idx_plan_features_plan ON plan_features(plan_id);

CREATE TABLE user_subscriptions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id            BIGINT      NOT NULL REFERENCES subscription_plans(id),
    status             VARCHAR(20) NOT NULL,
    started_at         TIMESTAMP,
    current_period_end TIMESTAMP,
    provider           VARCHAR(40),
    provider_ref       VARCHAR(200),
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP
);
CREATE INDEX idx_user_subscriptions_user_status ON user_subscriptions(user_id, status);
